config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show, :new, :create] do
    resources :payments, only: [:new, :create]
  end
 
  
  devise_for :users
  get 'render/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "render#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_payments, dependent: :destroy
  has_many :payments, through: :group_payments, dependent: :destroy

  validates :name, presence: true, length: { in: 1..250 }
  validates :icon, presence: true
end

app/models/group_payment.rb
class GroupPayment < ApplicationRecord
  belongs_to :group
  belongs_to :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_payments, dependent: :destroy
  has_many :groups, through: :group_payments, dependent: :destroy

  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :groups, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :payments, dependent: :destroy, foreign_key: 'author_id'
  has_many :groups, dependent: :destroy, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_out_path_for(_resource)
    render_index_path
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.order(id: :asc)
    @group = @groups.find_by_id(params[:id])
  end

  # GET /groups/1 or /groups/1.json
  def show
    @payments = @group.payments.order(created_at: :desc)
    @total = @payments.sum(:amount)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.author = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments/new
  def new
    @payment = Payment.new
    @groups = Group.all
    @group = Group.find(params[:group_id])

    if @group.author == current_user
      @payment = Payment.new
    else
      flash[:alert] = 'You can only create expenses from your categories'
      redirect_to groups_path
    end
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.author = current_user
    @groups = Group.where(id: group_params[:groups])
    @group = Group.find(params[:group_id])
    @payment.groups << @groups

    respond_to do |format|
      if @payment.save
        format.html { redirect_to group_url(@group), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  def group_params
    params.require(:payment).permit(groups: [])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/render_controller.rb
class RenderController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container my-5">
    <div class="field form-group">
      <%= form.label "Name", class: "col-sm-2 col-form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Icon", class: "col-sm-2 col-form-label" %>
      <%= form.text_field :icon, class: "form-control" %>
    </div>

    <div class="mt-5 d-flex justify-content-center">
      
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<%= render "layouts/nav" %>
<div id="categories" class="container bg-light">
    <% @groups.each do |category| %>
      <%= link_to group_path(category.id), class: "text-decoration-none" do %>
        <div class="container bg-white mt-4 shadow-lg p-3 mb-5 rounded">
          <div class="row">
            <div id="img-div" class="col"><img src=<%= category.icon%> alt=<%= category.name%> /></div>
            <div class="col">
              <p class = "fw-bold text-secondary fs-5 opacity-75"><%= category.name %><p>
              <p class = "fw-light text-secondary"><%= category.created_at.to_date.strftime('%Y %b %d') %></p>
            </div>
            <div class="col d-flex justify-content-end">
              <p class = "fw-bold text-dark fs-5">$<%= category.payments.sum(:amount) %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="mt-3 mb-5 d-flex justify-content-center">
    <%= link_to "New category", new_group_path, class: "btn btn-primary" %>
  </div>
  

app/views/groups/new.html.erb
<%= render "shared/nav", title: "NEW GROUP", info: '' %>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<%= render "shared/nav", title: "DETAILS", info: '' %>
<div>
    <div id="payments">
      <div class="d-flex container align-items-center border-bottom border-light border-4 mt-3 mb-5 pb-5">
        <div id="img-div" class="col">
          <img src=<%= @group.icon%> alt=<%= @group.name%> />
        </div>
        <div class="col">
          <p class = "fw-bold text-secondary fs-5 opacity-75"><%= @group.name %><p>
        </div>
      </div>
   
      <% @payments.each do |payment| %>
      <div class="container border-bottom border-light border-4 mt-3">
        <div class="d-flex justify-content-between align-items-center">
          <p class = "fw-light text-info fs-5">Transaction <%= payment.name %></p>
         
          <p class = "fw-bold text-dark fs-5">$ <%= payment.amount %></p>

        </div>
        <div class="d-flex align-items-baseline gap-2 ">
        <i class="fa fa-calendar" aria-hidden="true"></i>
        <p><%= payment.created_at.to_date.strftime('%Y %b %d') %> at <%= payment.created_at.to_time.strftime('%H:%M:%S') %></p>
        </div>
        
         
       </div>
  <% end %>
</div>
  </div>
  <div class="d-flex justify-content-between container mt-5">
    <p class = "fw-bold text-secondary fs-5">TOTAL PAYMENT</p>
    <p class = "fw-bold text-dark fs-5">$ <%= @total %></p>
  </div>
  <div class="my-5 d-flex justify-content-center">
    <%= link_to "New transaction", new_group_payment_path(@group), class: "btn btn-primary" %>
  </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="top-nav py-4">
<div class="container top">
  <div class="row">
  <div class="col">
   <button class="navbar-toggler ms-auto text-white" type="button" data-mdb-toggle="collapse"
      data-mdb-target="#navbarToggleExternalContent3" aria-controls="navbarToggleExternalContent3"
      aria-expanded="true" aria-label="Toggle navigation">
      <i class="fas fa-bars fs-1"></i>
    </button>
    </div>
    <div class="col">
    <h1 class="text-white">TRANSACTIONS</h1>
    </div>
    <div class="col justify-content-end d-flex">
   <div>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn sign-out-btn" %> 
    </div>
  	
    </div>
  </div>
  </div>
  
  <div class="d-flex justify-content-around mt-3 mb-3">
   <div class="d-flex  align-items-center text-white fs-3 fw-bold"> Welcome, <%= current_user.name %> </div>
   <div class="gap-3 d-flex">
      <button class="nav-btn">Most Recent</button>
      <button class="nav-btn">Most Ancient</button>
    </div>
    
  </div>
 
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
 
      <p class="notice position-absolute"><%= notice %></p>
      <p class="alert position-absolute"><%= alert %></p>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with model: @payment, url: group_payments_path do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="form-group">
    <div class="col-sm-10">
      <%= form.label :Name, class: "col-sm-2 col-form-label" %>
    </div>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control"  %>
    </div>
  </div>

   <div>
    <div class="form-group">
      <%= form.label :Amount, class: "col-sm-2 col-form-label" %>
    </div>
    <div class="col-sm-10">
      <%= form.number_field :amount, class: "form-control" %>
    </div>
  </div>

  <div>
    <div class="form-group">
      <%= form.label :Groups, class: "col-sm-2 col-form-label" %>
    </div>
    <div class="col-sm-10">
      <%= form.collection_select(:groups, current_user.groups, :id, :name, {}, { multiple: true, size: 7, class: "form-select" }) %>
    </div>
  </div>

  <div class="mt-5 d-flex justify-content-center">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/payments/_nav.html.erb
<nav class="navbar navbar-expand-lg top-nav justify-content-between text-white">
  <div class="mx-3">
      <%= link_to group_path(@group) do %>
        <i class="fa fa-arrow-left fs-1 text-white" aria-hidden="true"></i>
      <%end%>
  </div>
  <div class="fs-1">
      <%= title %>
  </div>
  <div class="mx-3 fs-4 btn text-white">
      <%= info %>
  </div>
</nav>

app/views/payments/new.html.erb
<%= render "nav", title: "NEW PAYMENT", info: '' %>

<%= render "form", payment: @payment, groups: @groups, group: @groups %>

app/views/render/index.html.erb
<main class="container">
  <div class="row text-center justify-content-center">
    <div class="max-vh-100 position-absolute top-50 start-50 translate-middle">
      <div class="py-5">
        <h1 class="fw-bolder mb-5 text-center">PaySafe<h1>
      </div>
      <div class="">
        <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary text-white mt-5 session-btn" %>
      </div>
      <div class="">
        <%= link_to "SIGN UP", new_user_registration_path, class: "btn session-btn register-btn" %>
      </div>
    </div>
  </div>
</main>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg top-nav justify-content-between text-white">
  <div class="mx-3">
      <%= link_to groups_path do %>
        <i class="fa fa-arrow-left fs-1 text-white" aria-hidden="true"></i>
      <%end%>
  </div>
  <div class="fs-1">
      <%= title %>
  </div>
  <div class="mx-3 fs-4 btn text-white">
      <%= info %>
  </div>
</nav>